version: '{build}'
   
build_script:
    - ps: |
        if ( !(Test-Path "$env:APPVEYOR_BUILD_FOLDER\appveyorHelp.psm1"))
        {
            Start-FileDownload https://raw.githubusercontent.com/TheOneRing/appVeyorHelp/master/appveyorHelp.psm1 -FileName $env:APPVEYOR_BUILD_FOLDER\appveyorHelp.psm1 
        }
        $ErrorActionPreference="Stop"
        Import-Module $env:APPVEYOR_BUILD_FOLDER\appveyorHelp.psm1
        
        Init @("ninja")
        mkdir -Force $env:APPVEYOR_BUILD_FOLDER\work\build\$env:APPVEYOR_PROJECT_NAME
        cd $env:APPVEYOR_BUILD_FOLDER\work\build\$env:APPVEYOR_PROJECT_NAME
        LogExec cmake -G"Ninja" $env:APPVEYOR_BUILD_FOLDER -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$CMAKE_INSTALL_ROOT"
        
        CmakeImageInstall
        7ZipDeployImage

test: off

cache:
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
    - appveyorHelp.psm1 -> appveyor.yml

environment:
    matrix:
    - COMPILER: msvc2013_32
    - COMPILER: msvc2013_64
    